<?php
/**
 * Custom block registration. Both blocks ship with no JS build step, so
 * editor scripts are registered by hand with explicit wp-* dependencies
 * instead of relying on block.json's file:-path auto-registration, which
 * only works when a matching .asset.php (generated by @wordpress/scripts)
 * sits next to the script.
 */

if (!defined('ABSPATH')) exit;

function sci_register_block_editor_scripts() {
	wp_register_script(
		'sci-calculator-editor',
		SCI_THEME_URI . '/blocks/calculator/edit.js',
		['wp-blocks', 'wp-element', 'wp-block-editor', 'wp-components', 'wp-server-side-render', 'wp-i18n'],
		SCI_VERSION,
		true
	);

	wp_register_script(
		'sci-accordion-editor',
		SCI_THEME_URI . '/blocks/accordion/edit.js',
		['wp-blocks', 'wp-element', 'wp-block-editor', 'wp-components', 'wp-i18n'],
		SCI_VERSION,
		true
	);
}
add_action('init', 'sci_register_block_editor_scripts');

function sci_register_blocks() {
	register_block_type(SCI_THEME_DIR . '/blocks/calculator');
	register_block_type(SCI_THEME_DIR . '/blocks/accordion');
	register_block_type(SCI_THEME_DIR . '/blocks/accordion/item');
}
add_action('init', 'sci_register_blocks');

/**
 * Renders a sci/accordion block (with sci/accordion-item children) from a
 * plain PHP array, for hardcoded template chrome (e.g. the FAQ on the
 * courses archive or contact page) that isn't backed by editable
 * post_content. Going through render_block() — instead of duplicating the
 * accordion markup as raw HTML — means these sections get the exact same
 * output as an editor-placed accordion and automatically pull in the
 * block's view.js (WordPress enqueues a block's viewScript whenever
 * WP_Block::render() runs, whether triggered by the_content() or this direct
 * call), so one toggle script serves every accordion on the site.
 *
 * @param array $items List of ['question' => string, 'answer' => string, 'open' => bool].
 */
function sci_render_accordion(array $items) {
	$inner_blocks  = [];
	$inner_content = [];

	foreach ($items as $item) {
		$inner_blocks[] = [
			'blockName'    => 'sci/accordion-item',
			'attrs'        => [
				'question'      => $item['question'],
				'answer'        => $item['answer'],
				'openByDefault' => !empty($item['open']),
			],
			'innerBlocks'  => [],
			'innerHTML'    => '',
			'innerContent' => [],
		];
		$inner_content[] = null;
	}

	return render_block([
		'blockName'    => 'sci/accordion',
		'attrs'        => [],
		'innerBlocks'  => $inner_blocks,
		'innerHTML'    => '',
		'innerContent' => $inner_content,
	]);
}
